---
-  name: Test de Nxos-leaf1
   hosts: leaf1
   gather_facts: no
   vars:
     features:
       - { id: ospf }
       - { id: vpc }
       - { id: lacp }
       - { id: interface-vlan }
       - { id: bgp }
       - { id: vn-segment-vlan-based }
       - { id: nv overlay }

   tasks:
   - name: Features activation
     cisco.nxos.nxos_feature:
       feature: "{{item.id}}"
       state: enabled
     loop: "{{features}}"

   - name: Configure to layer3
     cisco.nxos.nxos_interfaces:
       config:
       - name: Ethernet1/3
         description: Intercon leaf1 to spine
         enabled: true
         mode: layer3
       state: replaced

   - name: Interfaces config
     cisco.nxos.nxos_l3_interfaces:
       config:
       - name: "loopback1"
         ipv4:
         - address: "10.1.1.1/32"
       - name: "Ethernet1/3"
         ipv4:
         - address: "10.13.13.1/24"
       state: merged

   - name: Configure OSPFv2 Instance
     cisco.nxos.nxos_ospfv2:
       config:
         processes:
         - process_id: 999
           router_id: 10.1.1.1
           areas:
             - area_id: 0.0.0.0
               nssa:
                 default_information_originate: "true"
                 no_summary: "true"
       state: merged

   - name: Configure OSPFv2 Interfaces
     cisco.nxos.nxos_ospf_interfaces:
       config:
       - name: "loopback1"
         address_family:
         - afi: ipv4
           processes:
           - process_id: "999"
             area:
               area_id: 0.0.0.0
       - name: "Ethernet1/3"
         address_family:
         - afi: ipv4
           processes:
           - process_id: "999"
             area:
              area_id: 0.0.0.0
       state: merged

   - name: Configure EVPN Global
     cisco.nxos.nxos_evpn_global:
       nv_overlay_evpn: "true"


-  name: Test de Nxos-leaf2
   hosts: leaf2
   gather_facts: no
   vars:
     features:
       - { id: ospf }
       - { id: vpc }
       - { id: lacp }
       - { id: interface-vlan }
       - { id: bgp }
       - { id: vn-segment-vlan-based }
       - { id: nv overlay }

   tasks:

   - name: Features activation
     cisco.nxos.nxos_feature:
       feature: "{{item.id}}"
       state: enabled
     loop: "{{features}}"

   - name: Configure to layer3
     cisco.nxos.nxos_interfaces:
       config:
       - name: Ethernet1/3
         description: Intercon leaf2 to spine
         enabled: true
         mode: layer3
       state: replaced

   - name: Interfaces config
     cisco.nxos.nxos_l3_interfaces:
       config:
       - name: "loopback2"
         ipv4:
         - address: "10.2.2.2/32"
       - name: "Ethernet1/3"
         ipv4:
         - address: "10.23.23.2/24"
       state: merged

   - name: Configure OSPFv2 Instance
     cisco.nxos.nxos_ospfv2:
       config:
         processes:
         - process_id: 999
           router_id: 10.2.2.2
           areas:
             - area_id: 0.0.0.0
               nssa:
                 default_information_originate: "true"
                 no_summary: "true"
       state: merged

   - name: Configure OSPFv2 Interfaces
     cisco.nxos.nxos_ospf_interfaces:
       config:
       - name: "loopback2"
         address_family:
         - afi: ipv4
           processes:
           - process_id: "999"
             area:
               area_id: 0.0.0.0
       - name: "Ethernet1/3"
         address_family:
         - afi: ipv4
           processes:
           - process_id: "999"
             area:
              area_id: 0.0.0.0
       state: merged

   - name: Configure EVPN Global
     cisco.nxos.nxos_evpn_global:
       nv_overlay_evpn: "true"


-  name: Test de Nxos-Spine
   hosts: spine
   gather_facts: no
   vars:
     features:
       - { id: ospf }
       - { id: vpc }
       - { id: lacp }
       - { id: interface-vlan }
       - { id: bgp }
       - { id: vn-segment-vlan-based }
       - { id: nv overlay }

   tasks:

   - name: Features activation
     cisco.nxos.nxos_feature:
       feature: "{{item.id}}"
       state: enabled
     loop: "{{features}}"

   - name: Configure to layer3
     cisco.nxos.nxos_interfaces:
       config:
       - name: Ethernet1/1
         description: Intercon spine to leaf1
         enabled: true
         mode: layer3
       - name: Ethernet1/2
         description: Intercon spine to leaf2
         enabled: true
         mode: layer3
       state: replaced

   - name: Interfaces config
     cisco.nxos.nxos_l3_interfaces:
       config:
       - name: "loopback3"
         ipv4:
         - address: "10.3.3.3/32"
       - name: "Ethernet1/1"
         ipv4:
         - address: "10.13.13.3/24"
       - name: "Ethernet1/2"
         ipv4:
         - address: "10.23.23.3/24"
       state: merged

   - name: Configure OSPFv2 Instance
     cisco.nxos.nxos_ospfv2:
       config:
         processes:
         - process_id: 999
           router_id: 10.3.3.3
           areas:
             - area_id: 0.0.0.0
               nssa:
                 default_information_originate: "true"
                 no_summary: "true"
       state: merged

   - name: Configure OSPFv2 Interfaces
     cisco.nxos.nxos_ospf_interfaces:
       config:
       - name: "loopback3"
         address_family:
         - afi: ipv4
           processes:
           - process_id: "999"
             area:
               area_id: 0.0.0.0
       - name: "Ethernet1/1"
         address_family:
         - afi: ipv4
           processes:
           - process_id: "999"
             area:
              area_id: 0.0.0.0
       - name: "Ethernet1/2"
         address_family:
         - afi: ipv4
           processes:
           - process_id: "999"
             area:
              area_id: 0.0.0.0
       state: merged
